# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: David Goss
email: david@davidgoss.co
description: > # this means to ignore newlines until "baseurl:"
  The personal site of David Goss, a web developer from the UK
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://davidjgoss.github.io" # the base hostname & protocol for your site
twitter_username: davidjgoss
github_username:  davidjgoss

# Build settings
markdown: kramdown
